#' @title Net Compare Cross Species of WGCNA
#'
#' @description This package provides a WGCNA net cross species comparison method for an unspecified subset of genes. You need to provide WGCNA results for two species, including 'ConsonsusTOM block. 1. rda' and 'net'. Return four easily understandable visual network diagrams.
#' This project is based on cross species comparison between humans and mice, so the two species to be compared are referred to as humans and mice in this project. But we believe that this can also be directly applied to comparative studies of other species.

#' @param humangene,mousegene must be a one-to-one corresponding gene list to be analyzed. We understand that when conducting single-cell comparative studies, in order to merge data, gene names in the dataset are often converted to homologous genes from another species. Therefore, a pre gene list geneidlist was provided. This is manually generated by us based on existing public information, providing basic information on human and mouse gene correspondence. The first column is the code, the second column is the human gene, and the third column is the mouse gene. Based on the gene list, we provide automatic conversion of human and mouse genes; When you need similar name conversions compared to other species, please provide a generic list in a similar format.
#' @param humandata,mousedata fill in the file 'ConsonsusTOM block. 1. rda' of human or mouse, which includes the variable 'consTomDS'.
#' @param humannet,mousenet fill in the file 'net. rda' of human or mouse, which includes the variable 'net'.'consTomDS' and 'net' were generated during the execution of WGCNA. Just used for take names of genes in the whole TOMnetwork. A code example for generating such files is: net=blockwiseConsensusModules(multiExpr, blocks = NULL,...,saveConsensusTOMs = TRUE,consensusTOMFilePattern = "ConsensusTOM-block.1.rda")
#' @param humanmodcolor,mousemodcolor The color of the module which you analyzed.
#' @param k (=20) The multiple relationship between 'background adjacency' and 'important adjacency' can be adjusted by k.
#' @param linecoloralpha (=c(0.40,0.40,0.40,0.40)) The transparency of the lines in the image can be specified separately by adjusting the linecoloralpha, which is crucial for visualizing the results
#' @param mosttimes Specify the maximum range for searching for k values, default to 500
#' @param quitname output file name
#' @param means title in every picture
#' @param nettype how to take out gene names
#' @return 4 picture of net compare will be build in

#' @examples nccs(humangene_1,mousegene_1,humandata_1,mousedata_1,humannet_1,mousenet_1,humanmodcolor_1,mousemodcolor_1,k=20,linecoloralpha=c(0.4,0.3,0.4,0.3),mosttimes=500,quitname='result of nccsWGCNA',means=c("Human Transformational Adjacency Network","Mouse Transformational Adjacency Network","Human-Mouse Transformational Adjacency Network","Mouse-Human Transformational Adjacency Network"),nettype='net')
#' @import igraph
#' @import RColorBrewer
#' @export
#import
#install.packages('igraph')
#install.packages('RColorBrewer')
#library(igraph);
#library(RColorBrewer);
#load('./data/geneidlist.Rdata')
#load(humandatapwd_1)
#humanconsTomDS=consTomDS
#humandata_1=consTomDS
#load(mousedatapwd_1)
#mousedata_1=consTomDS
#mouseconsTomDS=consTomDS
#load(humannetpwd_1)
#humannet_1=net
#load(mousenetpwd_1)
#mousenet_1=net
#use_data(humandata_1,mousedata_1,humannet_1,mousenet_1)
#humangene=humangene_1
#mousegene=mousegene_1
#humandata=humandata_1
#mousedata=mousedata_1
#humannet=humannet_1
#mousenet=mousenet_1
#nccs(humangene_1,mousegene_1,humandata_1,mousedata_1,humannet_1,mousenet_1,humanmodcolor_1,mousemodcolor_1,k=20,linecoloralpha=c(0.4,0.3,0.4,0.3))


nccs<- function(humangene,mousegene,humandata,mousedata,humannet,mousenet,humanmodcolor,mousemodcolor,k=20,linecoloralpha=c(0.40,0.40,0.40,0.40),mosttimes=500,quitname='result of nccsWGCNA',means=c("Human Transformational Adjacency Network","Mouse Transformational Adjacency Network","Human-Mouse Transformational Adjacency Network","Mouse-Human Transformational Adjacency Network"),nettype='net') {
  humanconsTomDS=humandata
  mouseconsTomDS=mousedata

  humanTOM.matrix = as.matrix(humanconsTomDS)
  if (nettype=='net'){humannames2=unlist(attr(humannet$colors ,'names'))}
  if (nettype=='TOM'){humannames2=unlist(attr(humannet,'dimnames')[1])}


  mouseTOM.matrix = as.matrix(mouseconsTomDS)
  if (nettype=='net'){mousenames2=unlist(attr(mousenet$colors ,'names'))}
  if (nettype=='TOM'){mousenames2=unlist(attr(mousenet,'dimnames')[1])}

  generesult=unlist(list())
  genelist=humannames2
  species='human'
  if(length(union(genelist,unlist(geneidlist[3])))>length(union(genelist,unlist(geneidlist[2])))){#和人合并，显然并集小的为其现有归属
    flag=2
  }else{flag=3}
  #print(flag)
  if (species=="human"){
    generesult=unlist(list())
    for (i in (genelist)){
      generesult=append(generesult,unlist(geneidlist[2])[which(unlist(geneidlist[flag])== i)])
    }
  }
  if (species=='mouse'){
    generesult=unlist(list())
    for (i in (genelist)){
      generesult=append(generesult,unlist(geneidlist[3])[which(unlist(geneidlist[flag])== i)])
    }
  }
  humannames2=generesult
  generesult=unlist(list())
  genelist=mousenames2
  species='mouse'
  if(length(union(genelist,unlist(geneidlist[3])))>length(union(genelist,unlist(geneidlist[2])))){#和人合并，显然并集小的为其现有归属
    flag=2
  }else{flag=3}
  #print(flag)
  if (species=="mouse"){
    generesult=unlist(list())
    for (i in (genelist)){
      generesult=append(generesult,unlist(geneidlist[2])[which(unlist(geneidlist[flag])== i)])
    }
  }
  if (species=='mouse'){
    generesult=unlist(list())
    for (i in (genelist)){
      generesult=append(generesult,unlist(geneidlist[3])[which(unlist(geneidlist[flag])== i)])
    }
  }
  mousenames2=generesult

  colnames(humanTOM.matrix)=humannames2
  rownames(humanTOM.matrix)=humannames2
  colnames(mouseTOM.matrix)=mousenames2
  rownames(mouseTOM.matrix)=mousenames2

  humanreducedTOM = humanTOM.matrix[humangene[(humangene %in% humannames2)],humangene[(humangene %in% humannames2)]]
  mousereducedTOM = mouseTOM.matrix[mousegene[(mousegene %in% mousenames2)],mousegene[(mousegene %in% mousenames2)]]

  for (i in colnames(humanreducedTOM)){humanreducedTOM[i,i]=0.01}
  for (i in colnames(mousereducedTOM)){mousereducedTOM[i,i]=0.01}
  ghuman <- graph.adjacency(as.matrix(humanreducedTOM),mode="upper",weighted=TRUE,diag=FALSE)
  gmouse <- graph.adjacency(as.matrix(mousereducedTOM),mode="upper",weighted=TRUE,diag=FALSE)

  genenumber=length(humangene)
  numberA=floor(genenumber*2/5)
  gA <- graph.adjacency(as.matrix(humanreducedTOM[1:numberA,1:numberA]),mode="upper",weighted=TRUE,diag=FALSE)
  gB <- graph.adjacency(as.matrix(humanreducedTOM[(numberA+1):genenumber,(numberA+1):genenumber]),mode="upper",weighted=TRUE,diag=FALSE)
  layoutCircle <- rbind(layout.circle(gA)/2,layout.circle(gB))

  kh=1/mean(as.numeric(unlist(attr(table(humanreducedTOM),'dimnames')))[2:length(as.numeric(unlist(attr(table(humanreducedTOM),'dimnames'))))])

  for (i in seq(from=1,to=mosttimes,by=1)){
    humanreducedTOM3=((humanreducedTOM)*kh)^i/max(((humanreducedTOM)*kh)^i)*k
    if(mean(UpperExpansion(humanreducedTOM3))<1){
      #print(mean(UpperExpansion(humanreducedTOM3)))
      #print(i)
      humanhj1=i
      break
    }}


  for (i in seq(from=humanhj1-1.1,to=humanhj1+1.1,by=0.1)){
    humanreducedTOM3=((humanreducedTOM)*kh)^i/max(((humanreducedTOM)*kh)^i)*k
    if(mean(UpperExpansion(humanreducedTOM3))<1){
      #print(mean(UpperExpansion(humanreducedTOM3)))
      #print(i)
      humanhj2=i
      break
    }}

  for (i in seq(from=humanhj2-0.11,to=humanhj2+0.11,by=0.01)){
    humanreducedTOM3=((humanreducedTOM)*kh)^i/max(((humanreducedTOM)*kh)^i)*k
    if(mean(UpperExpansion(humanreducedTOM3))<1){
      #print(mean(UpperExpansion(humanreducedTOM3)))
      #print(i)
      humanhj3=i
      break
    }}


  for (i in seq(from=humanhj3-0.011,to=humanhj3+0.011,by=0.001)){
    humanreducedTOM3=((humanreducedTOM)*kh)^i/max(((humanreducedTOM)*kh)^i)*k
    if(mean(UpperExpansion(humanreducedTOM3))<1){
      #print(mean(UpperExpansion(humanreducedTOM3)))
      #print(i)
      humanhj4=i
      break
    }}

  for (i in seq(from=humanhj4-0.0011,to=humanhj4+0.0011,by=0.0001)){
    humanreducedTOM3=((humanreducedTOM)*kh)^i/max(((humanreducedTOM)*kh)^i)*k
    if(mean(UpperExpansion(humanreducedTOM3))<1){
      #print(mean(UpperExpansion(humanreducedTOM3)))
      #print(i)
      humanhj5=i
      break
    }}


  for (i in seq(from=humanhj5-0.00011,to=humanhj5+0.00011,by=0.00001)){
    humanreducedTOM3=((humanreducedTOM)*kh)^i/max(((humanreducedTOM)*kh)^i)*k
    if(mean(UpperExpansion(humanreducedTOM3))<1){
      #print(mean(UpperExpansion(humanreducedTOM3)))
      #print(i)
      humanhj6=i
      break
    }}

  for (i in seq(from=humanhj6-0.000011,to=humanhj6+0.000011,by=0.000001)){
    humanreducedTOM3=((humanreducedTOM)*kh)^i/max(((humanreducedTOM)*kh)^i)*k
    if(mean(UpperExpansion(humanreducedTOM3))<1){
      #print(mean(UpperExpansion(humanreducedTOM3)))
      #print(i)
      humanhj7=i
      break
    }}


  for (i in seq(from=humanhj7-0.0000011,to=humanhj7+0.0000011,by=0.0000001)){
    humanreducedTOM3=((humanreducedTOM)*kh)^i/max(((humanreducedTOM)*kh)^i)*k
    if(mean(UpperExpansion(humanreducedTOM3))<1){
      #print(mean(UpperExpansion(humanreducedTOM3)))
      #print(i)
      humanhj8=i
      break
    }}


  km=1/mean(as.numeric(unlist(attr(table(mousereducedTOM),'dimnames')))[2:length(as.numeric(unlist(attr(table(mousereducedTOM),'dimnames'))))])

  for (i in seq(from=1,to=mosttimes,by=1)){
    mousereducedTOM3=((mousereducedTOM)*km)^i/max(((mousereducedTOM)*km)^i)*k
    if(mean(UpperExpansion(mousereducedTOM3))<1){
      #print(mean(UpperExpansion(mousereducedTOM3)))
      #print(i)
      mousehj1=i
      break
    }}

  for (i in seq(from=mousehj1-1.1,to=mousehj1+1.1,by=0.1)){
    mousereducedTOM3=((mousereducedTOM)*km)^i/max(((mousereducedTOM)*km)^i)*k
    if(mean(UpperExpansion(mousereducedTOM3))<1){
      #print(mean(UpperExpansion(mousereducedTOM3)))
      #print(i)
      mousehj2=i
      break
    }}

  for (i in seq(from=mousehj2-0.11,to=mousehj2+0.11,by=0.01)){
    mousereducedTOM3=((mousereducedTOM)*km)^i/max(((mousereducedTOM)*km)^i)*k
    if(mean(UpperExpansion(mousereducedTOM3))<1){
      #print(mean(UpperExpansion(mousereducedTOM3)))
      #print(i)
      mousehj3=i
      break
    }}


  for (i in seq(from=mousehj3-0.011,to=mousehj3+0.011,by=0.001)){
    mousereducedTOM3=((mousereducedTOM)*km)^i/max(((mousereducedTOM)*km)^i)*k
    if(mean(UpperExpansion(mousereducedTOM3))<1){
      #print(mean(UpperExpansion(mousereducedTOM3)))
      #print(i)
      mousehj4=i
      break
    }}

  for (i in seq(from=mousehj4-0.0011,to=mousehj4+0.0011,by=0.0001)){
    mousereducedTOM3=((mousereducedTOM)*km)^i/max(((mousereducedTOM)*km)^i)*k
    if(mean(UpperExpansion(mousereducedTOM3))<1){
      #print(mean(UpperExpansion(mousereducedTOM3)))
      #print(i)
      mousehj5=i
      break
    }}


  for (i in seq(from=mousehj5-0.00011,to=mousehj5+0.00011,by=0.00001)){
    mousereducedTOM3=((mousereducedTOM)*km)^i/max(((mousereducedTOM)*km)^i)*k
    if(mean(UpperExpansion(mousereducedTOM3))<1){
      #print(mean(UpperExpansion(mousereducedTOM3)))
      #print(i)
      mousehj6=i
      break
    }}

  for (i in seq(from=mousehj6-0.000011,to=mousehj6+0.000011,by=0.000001)){
    mousereducedTOM3=((mousereducedTOM)*km)^i/max(((mousereducedTOM)*km)^i)*k
    if(mean(UpperExpansion(mousereducedTOM3))<1){
      #print(mean(UpperExpansion(mousereducedTOM3)))
      #print(i)
      mousehj7=i
      break
    }}


  for (i in seq(from=mousehj7-0.0000011,to=mousehj7+0.0000011,by=0.0000001)){
    mousereducedTOM3=((mousereducedTOM)*km)^i/max(((mousereducedTOM)*km)^i)*k
    if(mean(UpperExpansion(mousereducedTOM3))<1){
      #print(mean(UpperExpansion(mousereducedTOM3)))
      #print(i)
      mousehj8=i
      break
    }}

  humanfl=humanhj8
  humanreducedTOM2=((humanreducedTOM)*kh)^humanfl/max(((humanreducedTOM)*kh)^humanfl)*k
  mousefl=mousehj8
  mousereducedTOM2=((mousereducedTOM)*km)^mousefl/max(((mousereducedTOM)*km)^mousefl)*k

  tomm3=humanreducedTOM2-mousereducedTOM2
  tomm4=mousereducedTOM2-humanreducedTOM2

  #ghuman <- graph.adjacency(as.matrix(humanreducedTOM2),mode="undirected",diag=FALSE,weighted="directed")
  #genenumber=length(humangene)
  #numberA=floor(genenumber*2/5)
  #gA <- graph.adjacency(as.matrix(humanreducedTOM2[1:numberA,1:numberA]),mode="directed",weighted=TRUE,diag=FALSE)
  #gB <- graph.adjacency(as.matrix(humanreducedTOM2[(numberA+1):genenumber,(numberA+1):genenumber]),mode="directed",weighted=TRUE,diag=FALSE)
  #layoutCircle <- rbind(layout.circle(gA)/2,layout.circle(gB))
  #str(layoutCircle)
  pdf(paste0(quitname,'.pdf'),height=9,width=10)
  #pdf(paste0(quitname,'.pdf'),height=3,width=10/3)

  plot(ghuman,
       edge.color=adjustcolor(humanmodcolor, alpha.f=linecoloralpha[1]),
       edge.alpha=0.25,
       edge.width=UpperExpansion(humanreducedTOM2),
       vertex.color=adjustcolor(humanmodcolor, alpha.f=0.75),
       #vertex.label=as.character(submatrix$GeneSymbol),
       vertex.label=as.character(humangene),
       vertex.label.cex=1.1,
       vertex.label.dist=1.1,
       vertex.label.degree=-pi/4,
       vertex.label.color="black",
       #vertex.frame.color='black',
       layout= jitter(layoutCircle),
       vertex.size=6,
       #main=paste("human",humanmod,"module cluster ",humanclusternumber)
       main=paste(means[1])
  )

  plot(gmouse,
       edge.color=adjustcolor(mousemodcolor, alpha.f=linecoloralpha[2]),
       edge.alpha=0.25,
       edge.width=UpperExpansion(mousereducedTOM2),
       vertex.color=adjustcolor(mousemodcolor, alpha.f=0.75),
       #vertex.label=as.character(submatrix$GeneSymbol),
       vertex.label=as.character(mousegene),
       vertex.label.cex=1.1,
       vertex.label.dist=1.1,
       vertex.label.degree=-pi/4,
       vertex.label.color="black",
       #vertex.frame.color='black',
       layout= jitter(layoutCircle),
       vertex.size=6,
       #main=paste('mouse',mousemod,"module cluster ",mouseclusternumber)
       main=paste(means[2])
  )

  plot(ghuman,
       edge.color=adjustcolor(humanmodcolor, alpha.f=linecoloralpha[3]),
       edge.alpha=0.25,
       edge.width=UpperExpansion(tomm3),
       vertex.color=adjustcolor(humanmodcolor, alpha.f=0.75),
       #vertex.label=as.character(submatrix$GeneSymbol),
       vertex.label=as.character(humangene),
       vertex.label.cex=1.1,
       vertex.label.dist=1.1,
       vertex.label.degree=-pi/4,
       vertex.label.color="black",
       #vertex.frame.color='black',
       layout= jitter(layoutCircle),
       vertex.size=6,
       #main=paste("human",humanmod,"module cluster ",humanclusternumber,' - mouse',mousemod,'module cluster ',mouseclusternumber)
       main=paste(means[3])
  )

  plot(gmouse,
       edge.color=adjustcolor(mousemodcolor, alpha.f=linecoloralpha[4]),
       edge.alpha=0.25,
       edge.width=UpperExpansion(tomm4),
       vertex.color=adjustcolor(mousemodcolor, alpha.f=0.75),
       #vertex.label=as.character(submatrix$GeneSymbol),
       vertex.label=as.character(mousegene),
       vertex.label.cex=1.1,
       vertex.label.dist=1.1,
       vertex.label.degree=-pi/4,
       vertex.label.color="black",
       #vertex.frame.color='black',
       layout= jitter(layoutCircle),
       vertex.size=6,
       #main=paste('mouse',mousemod,"module cluster ",mouseclusternumber," - human",humanmod,'module cluster ',humanclusternumber)
       main=paste(means[4])
  )
  dev.off()
}
#加入参数图大小
